spring.application.name=webbanhang

# Cấu hình kết nối MySQL (Ví dụ database tên là sport_shop_db)
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
spring.datasource.username=root
spring.datasource.password=123456

# Tự động tạo bảng từ code Java (chỉ dùng khi dev, khi deploy nên tắt)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true